### ISSUE TITLE
Set up Pelican server

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#200]
~~Once I've migrated Kingfisher Archive files to S3, I'll start setting up this server.~~ Just putting some notes down.

**Comment by jpmckinney** [comment]
This will now be done by Datlab.

Once complete, we can delete our UptimeRobot account (and I can remove MFA token from app).

**Comment by jpmckinney** [comment]
When deploying Pelican to the Helpdesk server, need to re-add this service to docker-compose.yaml (relative to registry):

```
  vue:
    image: "ghcr.io/open-contracting/pelican-frontend-vue:latest"
    ports:
      - "8004:80"
    restart: unless-stopped
    volumes:
      - /data:/data
```

And set `CORS_ORIGIN_WHITELIST: https://pelican.open-contracting.org` and `TOKEN_PATH: /data/dqv/token.pickle` in Pillar.
