### ISSUE TITLE
hostnames: Fix onboarding to avoid multiple lines for the same IP addresses

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#214]
On Bytemark, this state will result in two lines for the IPv4 and IPv6 addresses: one line for the Bytemark hostname and another line for our hostname: https://github.com/open-contracting/deploy/blob/master/salt/onboarding.sls#L13-L22

The docs I can find suggest that there should be one line per IP address: https://man7.org/linux/man-pages/man5/hosts.5.html

Do we need to do a `file.replace` instead of `file.append`?

**Comment by RobHooper** [comment]
Ah right, I expect bytemark are setting this before we get it.
`/etc/hosts` will contain some default settings that we don't want to overwrite so we can't replace the entire file.

Perhaps adding a search for a pattern ending `bigv.io`, bytemarks hostname format.
```
example:
  file.replace:
    - name: /etc/hosts
    - pattern: ".*bigv.io"
    - repl: ...
```
