### ISSUE TITLE
Registry network (netplan) configuration

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#278]
The new registry server has been provisioned with two IP addresses 65.21.93.141 and 65.21.93.181, however the server is only configured to use one of them (65.21.93.181).

The DNS for ocp13.open-contracting.org has both of these IPs listed but since one isn't configured this means that there is a good chance deployments will fail. 

The server has also been provisioned with IPv6 however there are no DNS records for this.

@jpmckinney What is this secondary address being used for? do we need it?
If we do, we should reconfigure netplan on this server for both IPs.

We should also create new IPv6 DNS records.

**Comment by jpmckinney** [comment]
Ah, yes, 65.21.93.181 is for data.open-contracting.org and 65.21.93.141 is for flatten.open-contracting.org. Since they each configure their own webserver in Docker, one of which has more complex settings, we figured two IPs would be easier than adding a web server/load balancer in front of both. Please make the necessary configuration changes :)

I don't know the IPv6 addresses (I don't remember seeing them in robot.your-server.de), but I'm happy to add those to DNS.

**Comment by jpmckinney** [comment]
@myroslav I believe you have configured this? cc @sorenabell

**Comment by myroslav** [comment]
@jpmckinney we'd added additional IP on the server.

@anton-shakh-qg can you comment here what actions had you taken to add additional IP?

**Comment by shakhanton** [comment]
1. edited ` /etc/netplan/01-netcfg.yaml`
and added needed IP to the following block

```
...
  ethernets:
    enp9s0:
      addresses:
        - 65.21.93.181/32
        - 65.21.93.141/32
...
```
2. then ran the command `sudo netplan apply`

**Comment by RobHooper** [comment]
Confirming I've set up the IPv6 DNS records for amy01 and ocp13. 

I am unsure if the netplan configuration is something we want to add in salt?
If / when we re-deploying this registry service to future hardware we will probably have different IPs to configure anyway.
For the time being, I have documented the above actions in our server build guide. 

Other than the above question, the items in this issue are resolved.

**Comment by myroslav** [comment]
@RobHooper, IP address will also be part of spoonbill/flatten app config. It can be either ENV variable or entry in the .env file. So the IP is server dependent, but we cannot avoid it in neither in server's network config nor in the app config.

**Comment by jpmckinney** [comment]
@RobHooper Where is the server build guide?

I think it makes sense to add IPs to Salt. Since we don't have minions (#221), IPs are hardcoded in a few cases, so there is already precedent for updating IPs in Salt when changing servers.

**Comment by RobHooper** [comment]
@jpmckinney we have a server build guide in our internal wiki for each server listing the few things that have not or cannot be done with salt (some of our maintenance configuration with external services and one off commands like provisioning the replica1 kingfisher server with Hetzner).

**Comment by jpmckinney** [comment]
Sounds good. For netplan, I think it can be configured in Salt using `network.managed`? https://docs.saltproject.io/en/latest/ref/states/all/salt.states.network.html

**Comment by jpmckinney** [comment]
I've looked into this more. Salt doesn't support netplan yet - it uses Debian's `/etc/network/interfaces` instead.

The netplan file is created by Hetzner's installimage here: https://github.com/hetzneronline/installimage/blob/84883efa372b9c9ecef2bb7703d696221b4e1093/network_config.functions.sh#L560

I tried doing something like (note: I don't think the `content` will be properly indented with just this, but I didn't get far enough to find out):

```yaml
# Pillar file
+ips:
  - 65.21.93.181/32
  - 65.21.93.141/32
  - 2a01:4f9:3b:45ca::2/64
```

```jinja
# Salt file
{% if 'ips' in pillar %}
set addresses:
  file.blockreplace:
    - name: /etc/netplan/01-netcfg.yaml
    - marker_start: '      addresses:'
    - marker_end: '      routes:'
    - content: |
        - 65.21.93.181/32
        - 65.21.93.141/32
        - 2a01:4f9:3b:45ca::2/64
{% endif %}
```

However, it fails with:

```
Comment: Encountered error managing block: Unterminated marked block. End of file reached before marker_end.. See the log for details.
```

**Comment by RobHooper** [comment]
Salt not supporting netplan is concerning - I am very much worried about getting locked out of one of the Hetzner servers.
I think we can create alleviate some of this risk by creating a separate netplan file `/etc/netplan/additional-ips.yaml`.

I am about to need this functionality in salt to configure IPv6 on new Linode servers so that will be a nice place to test without effecting production.

**Comment by jpmckinney** [comment]
A new file sounds good. I'm not familiar enough with netplan, so had just attempted to edit the existing file via Salt.

**Comment by jpmckinney** [comment]
Noting that the registry can likely use this Pillar config (removed from #316):

```yaml
network:
  host_id: ocp13
  ipv4: 65.21.93.181
  ipv6: 2a01:4f9:3b:45ca::2
  netplan:
    configuration: custom
    ethernets:
      enp9s0:
        addresses:
          - 65.21.93.181/32
          - 65.21.93.141/32
          - 2a01:4f9:3b:45ca::2/64
        routes:
          - on-link: true
            to: 0.0.0.0/0
            via: 65.21.93.129
        gateway6: fe80::1
        nameservers:
          addresses:
            - 213.133.99.99
            - 213.133.100.100
            - 213.133.98.98
            - 2a01:4f8:0:1::add:9898
            - 2a01:4f8:0:1::add:9999
            - 2a01:4f8:0:1::add:1010
```
