### ISSUE TITLE
Failed to disable autoindex Apache module

### ISSUE THREAD

**Issue by dogsbody-rob** [open-contracting/deploy#446]
Seeing the following errors when deploying:
```
----------
          ID: autoindex
    Function: apache_module.disabled
      Result: False
     Comment: Failed to disable autoindex Apache module
     Started: 12:02:44.624481
    Duration: 31.62 ms
     Changes:   
...
----------
          ID: apache2
    Function: service.running
      Result: False
     Comment: One or more requisite failed: apache.autoindex
     Started: 12:02:44.661744
    Duration: 0.003 ms
     Changes:   
```
