### ISSUE TITLE
Why is pip frozen on Django projects?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#64]
`pip==8.1.2`

I figure we can at minimum use `>` instead of `==`.

**Comment by jpmckinney** [comment]
Given that we have unattended upgrades for apt packages, I figure we can allow pip to upgrade.

**Comment by jpmckinney** [comment]
Now that all Django apps use the same basic config (#63), I see that when deploying CoVE, this changed:

```
          ID: /home/cove/cove/.ve/
    Function: virtualenv.managed
      Result: True
     Comment: virtualenv exists
     Started: 18:23:46.978885
    Duration: 7365.353 ms
     Changes:   
              ----------
              packages:
                  ----------
                  new:
                      - pip==19.2.3
                  old:
                      - pip==8.1.2
```

i.e. 8.1.2 is ancient (2016).
