### ISSUE TITLE
Fix ssh_auth.absent failure when test=True

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#79]
e.g.

```
----------
          ID: root_authorized_keys_remove
    Function: ssh_auth.absent
      Result: False
     Comment: No keys detected in salt://private/authorized_keys/root_to_remove. Is file properly formatted?
     Started: 20:30:45.004857
    Duration: 2.0 ms
     Changes:   
```

It only occurs with `state.apply test=True`.

I figure this might be doable by putting a dummy value in `root_to_remove`? Need to test that it doesn't then complain about not matching a key.
